### ISSUE TITLE
Add Fibonacci sequence to recursive function readme!

### ISSUE THREAD

**Issue by RichAWarren** [codingforeveryone/READMEs#28]
It is definitely over done but it is a standard example case for why you should use recursive functions. I think it would be a great addition, especially considering there are numerous Codewars Fibonacci that you are likely to come across (and could be linked to!).

Would you be happy for me to add this in subject to your review?

**Comment by coudrew** [comment]
I've seen the fibonacci around a lot too, my only real concern is that it's a bit tricky to follow in your head when learning a new concept.

**Comment by daymos** [comment]
Can I add a  recursive function to calculate a factorial? It's pretty much a classic but it is very easy to understand.

**Comment by coudrew** [comment]
@daymos yes, please do :)

**Comment by daymos** [comment]
cool

**Comment by daymos** [comment]
Just created the pull request. Let me know if it's ok

**Comment by RichAWarren** [comment]
Just created a pull request for fibonacci. Tried explain as simple as possible, let me know if its okay! https://github.com/codingforeveryone/READMEs/pull/35

**Comment by coudrew** [comment]
the `this` in the calls to `recursive` isn't necessary, maybe also use function declarations instead of function expressions (just for consistency with the rest of the README). But otherwise that's pretty straightforward :) a lot of tuts I see that use Fibonacci are just full of long console logs, huge pain to follow. So thanks for not over-complicating!
