### ISSUE TITLE
References to images must be updated

### ISSUE THREAD

**Issue by gabrielperales** [codingforeveryone/READMEs#99]
The new structure of the repo has broken references to images on some READMEs. We have to update them, I have updated some, and I'm going to fix some more, but check if there are more to be update.

**Comment by cshg** [comment]
@gabrielperales good point. Thanks for pointing it out. Because of the links we shouldn't change the structure too often. There is another pull request with additional folder renaming, but we might just omit that one if it's not worth the additional bugfixing effort again (https://github.com/codingforeveryone/READMEs/pull/98)

**Comment by bradreeder** [comment]
I just reviewed the files and found only two broken images (array-map.md & setting-up-a-local-server.md). I've committed and made pull requests for the changes, so if you could merge I'll close the issue.

Thanks by the way. I was planning to look up how to fix this if no one else did, was just preoccupied this afternoon. :)

**Comment by bradreeder** [comment]
I've fixed the remaining broken images and the commits have been merged. Issue resolved.
